FROM node:alpine

WORKDIR '/usr/app/'

COPY ./package.json ./
RUN npm install

# COPY ./ ./

CMD ["npm","run","start"]

# docker build -f Dockerfile.dev .
# docker run -p 3000:3000 -v /usr/app/node_modules -v $(pwd):/usr/app <image-id>